# ifndef __ST_AUTOCOMPLETE_H
# define __ST_AUTOCOMPLETE_H

enum {
	ACMPL_DEACTIVATE,
	ACMPL_WORD,
	ACMPL_WWORD,
	ACMPL_FUZZY_WORD,
	ACMPL_FUZZY_WWORD,
	ACMPL_FUZZY,
	ACMPL_SUFFIX,
	ACMPL_SURROUND,
	ACMPL_UNDO,
};

# endif // __ST_AUTOCOMPLETE_H
