# fg bg b/u/r/i/c
# Vim editor colors

Base00:   'base00'
Base01:   'base01'
Base02:   'base02'
Base03:   'base03'
Base04:   'base04'
Base05:   'base05'
Base06:   'base06'
Base07:   'base07'
Base08:   'base08'
Base09:   'base09'
Base0A:   'base0A'
Base0B:   'base0B'
Base0C:   'base0C'
Base0D:   'base0D'
Base0E:   'base0E'
Base0F:   'base0F'
Base10:   'base10'

Bold:                       '. . b'
Debug:                      'base08 . .'
Directory:                  'base0D . .'
ErrorMsg:                   'base08 base00 .'
Exception:                  'base08 . .'
FoldColumn:                 '. base01 .'
Folded:                     'base03 base01 .'
IncSearch:                  'base01 base09 .'
# Italic:                     '. . i'
Italic:                     '. . u'
Macro:                      'base08 . .'
MatchParen:                 'base05 base03 .'
ModeMsg:                    'base0B . .'
MoreMsg:                    'base0B . .'
Question:                   'base0D . .'
Search:                     'base03 base0A .'
SpecialKey:                 'base03 . .'
TooLong:                    'base08 . .'
Underlined:                 'base08 . .'
Visual:                     '. base02 .'
VisualNOS:                  'base08 . .'
WarningMsg:                 'base08 . .'
WildMenu:                   'base10 base0D .'
Title:                      'base0D . '
Conceal:                    'base0D base00 .'
Cursor:                     'base00 base05 .'
NonText:                    'base03 . .'
Normal:                     'base05 base00 .'
LineNr:                     'base03 base01 .'
CursorLineNR:               'base10 base10 .'
SignColumn:                 'base03 base01 .'
StatusLine:                 'base04 base02 '
StatusLineNC:               'base03 base01 '
VertSplit:                  'base02 base02 '
ColorColumn:                '. base01 '
CursorColumn:               '. base01 '
CursorLine:                 '. base01 '
CursorLineNr:               'base03 base01 .'
PMenu:                      'base04 base01 '
PMenuSel:                   'base01 base04 .'
PmenuSbar:                  '. base02 .'
PmenuThumb:                 '. base07 .'
TabLine:                    'base03 base01 '
TabLineFill:                'base03 base01 '
TabLineSel:                 'base0B base01 '
helpExample:                'base0A . .'
helpCommand:                'base0A . .'

  # Standard syntax highlighting
Boolean:                    'base09 . .'
Character:                  'base08 . .'
# Comment:                    'base03 . i'
Comment:                    'base03 .'
Conditional:                'base0E . .'
Constant:                   'base09 . .'
Define:                     'base0E . '
Delimiter:                  'base0F . .'
Float:                      'base09 . .'
Function:                   'base0D . .'
Identifier:                 'base08 . '
Include:                    'base0D . .'
Keyword:                    'base0E . .'
Label:                      'base0A . .'
Number:                     'base09 . .'
Operator:                   'base05 . '
PreProc:                    'base0A . .'
Repeat:                     'base0A . .'
Special:                    'base0C . .'
SpecialChar:                'base0F . .'
Statement:                  'base08 . .'
StorageClass:               'base0A . .'
String:                     'base0B . .'
Structure:                  'base0E . .'
Tag:                        'base0A . .'
Todo:                       'base0A base01 .'
Type:                       'base0A . '
Typedef:                    'base0A . .'

  # Spelling highlighting
SpellBad:                   '. base00 c'
SpellLocal:                 '. base00 c'
SpellCap:                   '. base00 c'
SpellRare:                  '. base00 c'
