#!/usr/bin/env bash

echo '<b><span foreground="#3b8af6" face="UbuntuMono Nerd Font" size="12650">  SYSTEM INFO</span></b>'
echo '<b><span foreground="#3b8af6" face="UbuntuMono Nerd Font" size="12650">==============</span></b>'
echo ''
show_kernel=$(${HOME}/.config/conky/scripts/kernel_version.sh)
show_time=$(${HOME}/.config/conky/scripts/current_date.sh)
show_uptime=$(${HOME}/.config/conky/scripts/show_uptime.sh)
show_volume=$(${HOME}/.config/conky/scripts/get_volume.sh)
show_disk=$(${HOME}/.config/conky/scripts/disk_info.sh)
show_memory=$(${HOME}/.config/conky/scripts/mem_info.sh)
show_cpu=$(${HOME}/.config/conky/scripts/cpu_info.sh)
show_gpu=$(${HOME}/.config/conky/scripts/gpu_info.sh)
show_updates=$(${HOME}/.config/conky/scripts/checkUpdates.sh)
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Kernel:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_kernel}'</span></b>' 
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Time:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650"> '${show_time}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Uptime:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_uptime}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Volume:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_volume}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Disk:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_disk}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Memory:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_memory}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> CPU:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_cpu}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650"> ﬙ </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> GPU:</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_gpu}'</span></b>'
echo '<b><span foreground="#cf9c19" face="UbuntuMono Nerd Font" size="12650">  </span></b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Updates</span><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">' ${show_updates}'</span></b>'
echo ''
echo '<b><span foreground="#3b8af6" face="UbuntuMono Nerd Font" size="12650">  SWAY KEYBINDINGS</span></b>'
echo '<b><span foreground="#3b8af6" face="UbuntuMono Nerd Font" size="12650">===================</span></b>'
echo ''
echo '<b><b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super +   </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Kitty</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + space </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Float Window</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + f </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Fullscreen</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + p </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Wofi (Run Mode)</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + o </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Wofi (Drun Mode)</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + q </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Rofi (Window Mode)</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + d </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Dmenu</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + b </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Mozilla Firefox</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + n </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= PCManFM</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + t </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Wl-Screenshooter</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + g </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Geany</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + m </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Telegram</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + z </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Wf-Recorder</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + x </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Wdisplays</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + u </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Xterm</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + i </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= LXAppearance</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + c </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= NetworkManager</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + h </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Set Horizontal</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + v </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Set Vertical</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> ﱛ  </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Volume +5</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> ﱜ  </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Volume -5</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> ﱝ  </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Mute Volume</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + q </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Kill Window</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + j </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Focus Left</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + ; </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Focus Right</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + l </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Focus Up</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + k </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Focus Down</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + e </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Logout</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + דּ  + וּ  + l </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Screen-off</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + r </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Resize Window</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + j </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Switch Left</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + ; </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Switch Right</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + l </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Switch Up</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + וּ  + k </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Switch Down</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super + 1-9 </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Select Workspace</span></b>'
echo '<b><span foreground="#379838" face="UbuntuMono Nerd Font" size="12650">  </span></b><b><span foreground="#e25ee6" face="UbuntuMono Nerd Font" size="12650"> Super +   </span></b><b><span foreground="#9ca8ce" face="UbuntuMono Nerd Font" size="12650">= Menu Logout</span></b>'
#echo "</span>"
