#!/bin/bash

##############################################################
# dmenu_drun - dmenu script that simulates 'rofi -show drun' #
#                                                            #
# Author: q3aql <q3aql@duck.com>                             #
# Last update: 20-07-2022                                    #
##############################################################

# Configuration variables
load_theme_path="${HOME}/.dmenu"
load_themes="${load_theme_path}/themes"
load_theme_file="${load_theme_path}/load_theme"
load_desktop_files="${HOME}/.dmenu/desktop"
desktop_files="/usr/share/applications"
desktop_files_local="/usr/local/share/applications"
desktop_files_home="${HOME}/.local/share/applications"
desktop_files_flatpak="/var/lib/flatpak/exports/share/applications"

function load_theme() {
  if [ -f "${load_theme_file}" ] ; then
    source "${load_theme_file}"
  else
    mkdir -p "${load_theme_path}"
    mkdir -p "${load_themes}"
    echo "#!/bin/bash" > ${load_theme_file}
    echo "" >> ${load_theme_file}
    echo "NFCOLOR=\"#bbbbbb\"" >> ${load_theme_file}
    echo "NBCOLOR=\"#1f1f35\"" >> ${load_theme_file}
    echo "SFCOLOR=\"#eeeeee\"" >> ${load_theme_file}
    echo "SBCOLOR=\"#664477\"" >> ${load_theme_file}
    source "${load_theme_file}"
  fi
}

function list_desktop_files() {
  if [ -d "${desktop_files}" ] ; then
    ls -1 "${desktop_files}/" | grep ".desktop"
  fi
  if [ -d "${desktop_files_local}" ] ; then
    ls -1 "${desktop_files_local}/" | grep ".desktop"
  fi
  if [ -d "${desktop_files_home}" ] ; then
    ls -1 "${desktop_files_home}/" | grep ".desktop"
  fi
  if [ -d "${desktop_files_flatpak}" ] ; then
    ls -1 "${desktop_files_flatpak}/" | grep ".desktop"
  fi
}

function list_desktop_icons() {
  echo "  Scan New Desktop Files"
  ls -1 "${load_desktop_files}/" | while read current_desktop ; do
    echo "  ${current_desktop}"
  done
}

function rundesk () {
  if [ -z ${1} ] ; then
    echo "No file entry"
  else
    if [ -f "${1}" ] ; then
      eval "$(awk -F= '$1=="Exec"{$1=""; print}' "$1" | head -1)"
    else
      echo "File does not exist"
    fi
  fi
}

function create_list_files() {
  mkdir -p ${load_desktop_files}
  if [ ! -f ${HOME}/.dmenu/read_list ] ; then
    echo "0" > ${HOME}/.dmenu/read_list
  fi
  exec_list=$(cat ${HOME}/.dmenu/read_list)
  if [ ${exec_list} -eq 0 ] ; then
    rm -rf ${load_desktop_files}/*
    list_desktop_files | while read current_file ; do
      if [ -f "${desktop_files}/${current_file}" ] ; then
        name_show=$(cat "${desktop_files}/${current_file}" | grep "Name=" | head -1 | cut -d "=" -f 2 | sed 's/\//|/g')
        if [ ! -z "${name_show}" ] ; then
          echo "${desktop_files}/${current_file}" > "${load_desktop_files}/${name_show}"
        fi
      fi
      if [ -f "${desktop_files_local}/${current_file}" ] ; then
        name_show=$(cat "${desktop_files_local}/${current_file}" | grep "Name=" | head -1 | cut -d "=" -f 2 | sed 's/\//|/g')
        if [ ! -z "${name_show}" ] ; then
          echo "${desktop_files_local}/${current_file}" > "${load_desktop_files}/${name_show}"
        fi
      fi
      if [ -f "${desktop_files_home}/${current_file}" ] ; then
        name_show=$(cat "${desktop_files_home}/${current_file}" | grep "Name=" | head -1 | cut -d "=" -f 2 | sed 's/\//|/g')
        if [ ! -z "${name_show}" ] ; then 
          echo "${desktop_files_home}/${current_file}" > "${load_desktop_files}/${name_show}"
        fi
      fi
      if [ -f "${desktop_files_flatpak}/${current_file}" ] ; then
        name_show=$(cat "${desktop_files_flatpak}/${current_file}" | grep "Name=" | head -1 | cut -d "=" -f 2 | sed 's/\//|/g')
        if [ ! -z "${name_show}" ] ; then 
          echo "${desktop_files_flatpak}/${current_file}" > "${load_desktop_files}/${name_show}"
        fi
      fi
    done
    echo "1" > ${HOME}/.dmenu/read_list 
  fi
}

if [ -f /usr/bin/dex ] ; then
  runDesktop="dex"
else
  runDesktop="rundesk"
fi

load_theme
create_list_files
list_output=$(list_desktop_icons | dmenu -i -nb "${NBCOLOR}" -nf "${NFCOLOR}" -sb "${SBCOLOR}" -sf "${SFCOLOR}" -l 18 -p " drun:")
run_output=$(echo ${list_output} | cut -c 5-999)
if [ ! -z "${run_output}" ] ; then
  if [ "${run_output}" == "Scan New Desktop Files" ] ; then
    echo "0" > ${HOME}/.dmenu/read_list
    create_list_files
    $0
  else
    run_desktop_file=$(cat "${load_desktop_files}/${run_output}")
    ${runDesktop} "${run_desktop_file}"
  fi
fi
