#!/bin/bash

user_loaded=$(whoami)
echo -e "                          "
echo -e "\e[31m         :.         .:      \e[0m"      
echo -e "\e[31m      .=:             :=.   \e[0m"   
echo -e "\e[31m     -+                 =-  \e[0m"  
echo -e "\e[31m    :#                   *- \e[0m" 
echo -e "\e[31m    @=                   :@ \e[0m"
echo -e "\e[31m   .@-                   :@:\e[0m"
echo -e "\e[31m    @*                   *@.\e[0m"
echo -e "\e[31m    #@*      :=++:      =@# \e[0m"
echo -e "\e[31m     #@#:     *@#     .#@%  \e[0m"
echo -e "\e[31m      =%@%=:  *@*  :=%@@+   \e[0m"
echo -e "\e[31m        -#@@@@@@@@@@@%+     \e[0m"
echo -e "\e[31m           .=+%@@+=-.       \e[0m"
echo -e "\e[31m              *@#           \e[0m"
echo -e "\e[31m              +@*           \e[0m"
echo -e "\e[31m              :@:           \e[0m"
echo -e "\e[31m               %            \e[0m"
echo -e "\e[31m                            \e[0m"
echo -e "\e[32m # Bienvenido al terminal de ${user_loaded}\e[0m"
echo -e -n "\e[35m # Cargando el terminal / \e[0m"
echo ""
